'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const stage=fs.readFileSync('assisted-access/stage210-dev-integration.js','utf8');
const view=fs.readFileSync('assisted-access/member-view.js','utf8');
const router=fs.readFileSync('assisted-access/router.js','utf8');
const chain=fs.readFileSync('stage51-patch.js','utf8');
assert.match(stage,/OPEN MEMBER ACCOUNT/);
assert.match(stage,/memberLookupFreshGrid\(bal\)/);
assert.match(stage,/tmcsOpenAssistedMemberV210/);
assert.match(view,/RETURN TO ADMIN/);
assert.match(router,/router\.get\('\/dashboard'/);
assert.match(router,/readOnly:true/);
assert.match(router,/router\.get\('\/history'/);
assert.match(router,/WHERE a\.member_account_id=\$1/);
assert.match(router,/performed_by/);
assert.doesNotMatch(chain,/require\('\.\/assisted-access\/stage210-dev-integration\.js'\)/);
console.log('PASS: staged read-only assisted Member Search integration checks.');
